# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
algos_sigma.o algos_sigma_m.mod: \
	$(COMMON)/algos_common_m.mod \
	$(COMMON)/message_m.mod \
	$(COMMON)/peinfo_m.mod \
	$(COMMON)/push_pop_m.mod
ch_converge.o ch_converge_m.mod: \
	$(COMMON)/global_m.mod
epscopy.o epscopy_m.mod: \
	$(COMMON)/epsread_hdf5_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scalapack_m.mod \
	$(COMMON)/timing_m.mod
genwf_mpi.o genwf_mpi_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/susymmetries_m.mod
input.o input_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/createpools_m.mod \
	$(COMMON)/epsread_hdf5_m.mod \
	$(COMMON)/eqpcor_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/read_rho_vxc_m.mod \
	$(COMMON)/scissors_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	genwf_mpi_m.mod \
	inread_m.mod
input_outer.o input_outer_m.mod: \
	$(COMMON)/eqpcor_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scissors_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
inread.o inread_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/inread_common_m.mod \
	$(COMMON)/references_m.mod \
	$(COMMON)/scissors_m.mod \
	algos_sigma_m.mod
mtxel.o mtxel_m.mod: \
	$(COMMON)/accel_fft_m.mod \
	$(COMMON)/accel_memory_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	algos_sigma_m.mod
mtxel_cor.o mtxel_cor_m.mod: \
	$(COMMON)/accel_linalg_m.mod \
	$(COMMON)/accel_memory_m.mod \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/timing_m.mod \
	algos_sigma_m.mod \
	wpeff_m.mod
mtxel_occ.o mtxel_occ_m.mod: \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
mtxel_vxc.o mtxel_vxc_m.mod: \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
offdiag.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/lapack_m.mod
offdiag_QSGW.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/lapack_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
shiftenergy.o shiftenergy_m.mod: \
	$(COMMON)/global_m.mod
shiftenergy_dyn.o shiftenergy_dyn_m.mod: \
	$(COMMON)/global_m.mod
sig2wan.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
sigma_main.o : \
	$(COMMON)/accel_fft_m.mod \
	$(COMMON)/check_screening_m.mod \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/checkgriduniformity_m.mod \
	$(COMMON)/epsread_hdf5_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/fixwings_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/irrbz_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/references_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/subgrp_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/vcoul_generator_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	$(COMMON)/write_program_header_m.mod \
	algos_sigma_m.mod \
	ch_converge_m.mod \
	epscopy_m.mod \
	genwf_mpi_m.mod \
	input_m.mod \
	input_outer_m.mod \
	mtxel_cor_m.mod \
	mtxel_m.mod \
	mtxel_occ_m.mod \
	mtxel_vxc_m.mod \
	shiftenergy_dyn_m.mod \
	shiftenergy_m.mod \
	write_result_dyn_hp_m.mod \
	write_result_dyn_m.mod \
	write_result_hp_m.mod \
	write_result_m.mod
sympert.o : \
	$(COMMON)/blas_m.mod \
	$(COMMON)/find_kpt_match_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	sympert_phonon_m.mod \
	sympert_utils_m.mod
sympert_phonon.o sympert_phonon_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod
sympert_utils.o sympert_utils_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/sort_m.mod \
	sympert_phonon_m.mod
wpeff.o wpeff_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
write_result.o write_result_m.mod: \
	$(COMMON)/global_m.mod
write_result_dyn.o write_result_dyn_m.mod: \
	$(COMMON)/global_m.mod
write_result_dyn_hp.o write_result_dyn_hp_m.mod: \
	$(COMMON)/global_m.mod
write_result_hp.o write_result_hp_m.mod: \
	$(COMMON)/global_m.mod

#Link dependencies:
offdiag.x offdiag$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/lapack.o \
	offdiag.o
offdiag_QSGW.x offdiag_QSGW$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/lapack.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	offdiag_QSGW.o
sig2wan.x sig2wan$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/misc.o \
	sig2wan.o
sigma.x sigma$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/accel_fft.o \
	$(COMMON)/accel_linalg.o \
	$(COMMON)/accel_memory.o \
	$(COMMON)/algos_common.o \
	$(COMMON)/bessel.o \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/check_screening.o \
	$(COMMON)/checkbz.o \
	$(COMMON)/checkgriduniformity.o \
	$(COMMON)/createpools.o \
	$(COMMON)/epsread_hdf5.o \
	$(COMMON)/eqpcor.o \
	$(COMMON)/fft_parallel.o \
	$(COMMON)/fftw.o \
	$(COMMON)/fixwings.o \
	$(COMMON)/fullbz.o \
	$(COMMON)/gmap.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/inread_common.o \
	$(COMMON)/io_utils.o \
	$(COMMON)/irrbz.o \
	$(COMMON)/message.o \
	$(COMMON)/minibzaverage.o \
	$(COMMON)/misc.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/read_rho_vxc.o \
	$(COMMON)/references.o \
	$(COMMON)/scalapack.o \
	$(COMMON)/scissors.o \
	$(COMMON)/sort.o \
	$(COMMON)/splines.o \
	$(COMMON)/subgrp.o \
	$(COMMON)/susymmetries.o \
	$(COMMON)/timing.o \
	$(COMMON)/trunc_cell_box.o \
	$(COMMON)/trunc_cell_box_d.o \
	$(COMMON)/trunc_cell_wire.o \
	$(COMMON)/trunc_scell_box_d.o \
	$(COMMON)/typedefs.o \
	$(COMMON)/vcoul_generator.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	algos_sigma.o \
	ch_converge.o \
	epscopy.o \
	genwf_mpi.o \
	input.o \
	input_outer.o \
	inread.o \
	mtxel.o \
	mtxel_cor.o \
	mtxel_occ.o \
	mtxel_vxc.o \
	shiftenergy.o \
	shiftenergy_dyn.o \
	sigma_main.o \
	wpeff.o \
	write_result.o \
	write_result_dyn.o \
	write_result_dyn_hp.o \
	write_result_hp.o
sympert.x sympert$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/find_kpt_match.o \
	$(COMMON)/gmap.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/io_utils.o \
	$(COMMON)/misc.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	sympert.o \
	sympert_phonon.o \
	sympert_utils.o
