# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
abi2bgw.o abi2bgw_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	print_error_m.mod \
	read_abi_m.mod \
	reciprocal_lattice_m.mod
abi2bgw_main.o : \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	abi2bgw_m.mod \
	read_abi_m.mod
check_eig.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	abi2bgw_m.mod \
	read_abi_m.mod
eqp_convert.o : \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	abi2bgw_m.mod \
	print_error_m.mod \
	read_abi_m.mod \
	read_eqp_m.mod
getbox.o : \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	abi2bgw_m.mod \
	read_abi_m.mod
print_error.o print_error_m.mod: \
	$(COMMON)/global_m.mod
read_abi.o read_abi_m.mod: \
	$(COMMON)/global_m.mod \
	print_error_m.mod
read_eqp.o read_eqp_m.mod: \
	$(COMMON)/global_m.mod
reciprocal_lattice.o reciprocal_lattice_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	print_error_m.mod

#Link dependencies:
abi2bgw.x abi2bgw$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/fftw.o \
	$(COMMON)/message.o \
	$(COMMON)/misc.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/sort.o \
	$(COMMON)/timing.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	abi2bgw.o \
	abi2bgw_main.o \
	print_error.o \
	read_abi.o \
	reciprocal_lattice.o
check_eig.x check_eig$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/misc.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	abi2bgw.o \
	check_eig.o \
	print_error.o \
	read_abi.o \
	reciprocal_lattice.o
eqp_convert.x eqp_convert$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/fftw.o \
	$(COMMON)/message.o \
	$(COMMON)/misc.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/sort.o \
	$(COMMON)/timing.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	abi2bgw.o \
	eqp_convert.o \
	print_error.o \
	read_abi.o \
	read_eqp.o \
	reciprocal_lattice.o
getbox.x getbox$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/fftw.o \
	$(COMMON)/message.o \
	$(COMMON)/misc.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/sort.o \
	$(COMMON)/timing.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	abi2bgw.o \
	getbox.o \
	print_error.o \
	read_abi.o \
	reciprocal_lattice.o
