# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
name.o name_m.mod: \
	$(COMMON)/global_m.mod
real.o real_m.mod: \
	$(COMMON)/global_m.mod
siesta2bgw.o : \
	$(COMMON)/check_inversion_m.mod \
	$(COMMON)/fft_parallel_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/norm_m.mod \
	$(COMMON)/read_cube_m.mod \
	$(COMMON)/symmetries_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	$(COMMON)/write_program_header_m.mod \
	name_m.mod \
	real_m.mod

#Link dependencies:
siesta2bgw.x siesta2bgw$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/fft_parallel.o \
	$(COMMON)/fftw.o \
	$(COMMON)/message.o \
	$(COMMON)/misc.o \
	$(COMMON)/norm.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/read_cube.o \
	$(COMMON)/sort.o \
	$(COMMON)/symmetries.o \
	$(COMMON)/timing.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	name.o \
	real.o \
	siesta2bgw.o
