# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
band.o band_m.mod: \
	$(COMMON)/global_m.mod \
	iolib_m.mod
bgw2para.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	band_m.mod \
	iolib_m.mod
iolib.o iolib_m.mod: \
	$(COMMON)/global_m.mod
rho2cd.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod

#Link dependencies:
bgw2para.x bgw2para$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	band.o \
	bgw2para.o \
	iolib.o
rho2cd.x rho2cd$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	rho2cd.o
