# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
analyzebz.o : \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/irrbz_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/subgrp_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
compute_vcoul.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/vcoul_generator_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod
degeneracy_check.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
extract_vcoul.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/vcoul_generator_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod
fix_occ.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
hdf2wfn.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
mf_convert.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
real2complex.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
scissors2eqp.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/scissors_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfn2hdf.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfn_dotproduct.o : \
	$(COMMON)/blas_m.mod \
	$(COMMON)/find_kpt_match_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfn_modify_spinor.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfn_rho_vxc_info.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfn_time_reversal.o : \
	$(COMMON)/find_kpt_match_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfnmerge.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfnmix_QSGW.o : \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfnmix_spinor.o : \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/random_m.mod \
	$(COMMON)/susymmetries_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfnmix_spinor_rho_vxc.o : \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfnreduce.o : \
	$(COMMON)/blas_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
wfnreduce.BM.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod

#Link dependencies:
analyzebz.x analyzebz$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/fullbz.o \
	$(COMMON)/irrbz.o \
	$(COMMON)/misc.o \
	$(COMMON)/sort.o \
	$(COMMON)/subgrp.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	analyzebz.o
compute_vcoul.x compute_vcoul$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/bessel.o \
	$(COMMON)/blas.o \
	$(COMMON)/fft_parallel.o \
	$(COMMON)/fftw.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/message.o \
	$(COMMON)/minibzaverage.o \
	$(COMMON)/misc.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/sort.o \
	$(COMMON)/timing.o \
	$(COMMON)/trunc_cell_box.o \
	$(COMMON)/trunc_cell_box_d.o \
	$(COMMON)/trunc_cell_wire.o \
	$(COMMON)/trunc_scell_box_d.o \
	$(COMMON)/vcoul_generator.o \
	$(COMMON)/wfn_io_hdf5.o \
	compute_vcoul.o
degeneracy_check.x degeneracy_check$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	degeneracy_check.o
extract_vcoul.x extract_vcoul$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/bessel.o \
	$(COMMON)/blas.o \
	$(COMMON)/fft_parallel.o \
	$(COMMON)/fftw.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/message.o \
	$(COMMON)/minibzaverage.o \
	$(COMMON)/misc.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/sort.o \
	$(COMMON)/timing.o \
	$(COMMON)/trunc_cell_box.o \
	$(COMMON)/trunc_cell_box_d.o \
	$(COMMON)/trunc_cell_wire.o \
	$(COMMON)/trunc_scell_box_d.o \
	$(COMMON)/vcoul_generator.o \
	$(COMMON)/wfn_io_hdf5.o \
	extract_vcoul.o
fix_occ.x fix_occ$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	fix_occ.o
hdf2wfn.x hdf2wfn$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/io_utils.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	hdf2wfn.o
mf_convert.x mf_convert$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	mf_convert.o
real2complex.x real2complex$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	real2complex.o
scissors2eqp.x scissors2eqp$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/scissors.o \
	$(COMMON)/sort.o \
	$(COMMON)/splines.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	scissors2eqp.o
wfn2hdf.x wfn2hdf$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/io_utils.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfn2hdf.o
wfn_dotproduct.x wfn_dotproduct$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/find_kpt_match.o \
	$(COMMON)/gmap.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/misc.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfn_dotproduct.o
wfn_modify_spinor.x wfn_modify_spinor$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfn_modify_spinor.o
wfn_rho_vxc_info.x wfn_rho_vxc_info$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfn_rho_vxc_info.o
wfn_time_reversal.x wfn_time_reversal$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/find_kpt_match.o \
	$(COMMON)/misc.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfn_time_reversal.o
wfnmerge.x wfnmerge$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfnmerge.o
wfnmix_QSGW.x wfnmix_QSGW$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/misc.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfnmix_QSGW.o
wfnmix_spinor.x wfnmix_spinor$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/misc.o \
	$(COMMON)/random.o \
	$(COMMON)/sort.o \
	$(COMMON)/susymmetries.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfnmix_spinor.o
wfnmix_spinor_rho_vxc.x wfnmix_spinor_rho_vxc$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/misc.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfnmix_spinor_rho_vxc.o
wfnreduce.x wfnreduce$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/fftw.o \
	$(COMMON)/message.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/sort.o \
	$(COMMON)/timing.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfnreduce.o
wfnreduce_BM.x wfnreduce_BM$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	wfnreduce.BM.o
