# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
compute_gss.o compute_gss_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod
exciton_phonon.o : \
	$(COMMON)/evecs_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/write_program_header_m.mod \
	compute_gss_m.mod \
	gkq_m.mod \
	xct_ph_maps_m.mod
gkq.o gkq_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod
gsq.o gsq_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod
print_gkq.o : \
	gkq_m.mod
test_gkq.o : \
	$(COMMON)/hdf5_io_m.mod \
	gkq_m.mod
xct_ph_maps.o xct_ph_maps_m.mod: \
	$(COMMON)/evecs_m.mod \
	$(COMMON)/global_m.mod \
	gkq_m.mod

#Link dependencies:
exciton_phonon.x exciton_phonon$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/evecs.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/io_utils.o \
	$(COMMON)/message.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/write_program_header.o \
	compute_gss.o \
	exciton_phonon.o \
	gkq.o \
	xct_ph_maps.o
print_gkq.x print_gkq$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	gkq.o \
	print_gkq.o
test_gkq.x test_gkq$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	gkq.o \
	test_gkq.o
