# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
absp3d.o absp3d_m.mod: \
	$(COMMON)/global_m.mod
absp_tp.o absp_tp_m.mod: \
	$(COMMON)/global_m.mod
absp_uf.o absp_uf_m.mod: \
	$(COMMON)/global_m.mod
distrib.o distrib_m.mod: \
	$(COMMON)/global_m.mod
input.o input_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scissors_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	distrib_m.mod
input_q.o input_q_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
inread.o inread_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/scissors_m.mod
nonlinearoptics.o : \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/genwf_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/mtxel_optical_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/write_program_header_m.mod \
	absp3d_m.mod \
	absp_tp_m.mod \
	absp_uf_m.mod \
	input_m.mod \
	input_q_m.mod \
	inread_m.mod \
	readasvck_tp_m.mod \
	readasvck_uf_m.mod
oscstrength.o oscstrength_m.mod: \
	$(COMMON)/global_m.mod
readasvck_tp.o readasvck_tp_m.mod: \
	$(COMMON)/evecs_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/timing_m.mod \
	oscstrength_m.mod
readasvck_uf.o readasvck_uf_m.mod: \
	$(COMMON)/evecs_m.mod \
	$(COMMON)/global_m.mod \
	oscstrength_m.mod

#Link dependencies:
nonlinearoptics.x nonlinearoptics$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/checkbz.o \
	$(COMMON)/evecs.o \
	$(COMMON)/fullbz.o \
	$(COMMON)/genwf.o \
	$(COMMON)/gmap.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/message.o \
	$(COMMON)/misc.o \
	$(COMMON)/mtxel_optical.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/scissors.o \
	$(COMMON)/sort.o \
	$(COMMON)/splines.o \
	$(COMMON)/susymmetries.o \
	$(COMMON)/timing.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	absp3d.o \
	absp_tp.o \
	absp_uf.o \
	distrib.o \
	input.o \
	input_q.o \
	inread.o \
	nonlinearoptics.o \
	oscstrength.o \
	readasvck_tp.o \
	readasvck_uf.o
