# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
SAPO_main.o : \
	$(COMMON)/check_inversion_m.mod \
	$(COMMON)/fft_parallel_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/groupk_m.mod \
	$(COMMON)/norm_m.mod \
	$(COMMON)/random_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/symmetries_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	$(COMMON)/write_program_header_m.mod \
	hdiag_m.mod \
	ortho_m.mod \
	pw_m.mod
hdiag.o hdiag_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/fft_parallel_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/lapack_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scalapack_m.mod \
	pw_m.mod
ortho.o ortho_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/sort_m.mod
pw.o pw_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/groupk_m.mod \
	$(COMMON)/lapack_m.mod \
	$(COMMON)/random_m.mod \
	$(COMMON)/sort_m.mod

#Link dependencies:
sapo.x sapo$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/fft_parallel.o \
	$(COMMON)/fftw.o \
	$(COMMON)/groupk.o \
	$(COMMON)/lapack.o \
	$(COMMON)/message.o \
	$(COMMON)/misc.o \
	$(COMMON)/norm.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/scalapack.o \
	$(COMMON)/sort.o \
	$(COMMON)/symmetries.o \
	$(COMMON)/timing.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	SAPO_main.o \
	hdiag.o \
	ortho.o \
	pw.o
