# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
distrib.o distrib_m.mod: \
	$(COMMON)/global_m.mod
input.o input_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	distrib_m.mod \
	input_common_m.mod \
	plotxct_common_m.mod
input_common.o input_common_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
input_q.o input_q_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	input_common_m.mod \
	plotxct_common_m.mod
inread.o inread_m.mod: \
	$(COMMON)/global_m.mod \
	plotxct_common_m.mod
inreaddens.o inreaddens_m.mod: \
	$(COMMON)/global_m.mod \
	plotxct_common_m.mod
interpol.o interpol_m.mod: \
	$(COMMON)/global_m.mod
plotxct.o : \
	$(COMMON)/evecs_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/genwf_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/random_m.mod \
	$(COMMON)/references_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/susymmetries_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/write_program_header_m.mod \
	input_m.mod \
	input_q_m.mod \
	inread_m.mod \
	interpol_m.mod \
	plotxct_common_m.mod \
	read_wannier_m.mod \
	write_xct_m.mod
plotxct_common.o plotxct_common_m.mod: \
	$(COMMON)/global_m.mod
plotxctdens.o : \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/genwf_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/write_program_header_m.mod \
	input_m.mod \
	input_q_m.mod \
	inreaddens_m.mod \
	plotxct_common_m.mod \
	write_xct_dens_m.mod
read_wannier.o read_wannier_m.mod: \
	$(COMMON)/global_m.mod
write_xct.o write_xct_m.mod: \
	$(COMMON)/global_m.mod \
	plotxct_common_m.mod
write_xct_dens.o write_xct_dens_m.mod: \
	$(COMMON)/global_m.mod \
	plotxct_common_m.mod

#Link dependencies:
plotxct.x plotxct$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/checkbz.o \
	$(COMMON)/evecs.o \
	$(COMMON)/fftw.o \
	$(COMMON)/fullbz.o \
	$(COMMON)/genwf.o \
	$(COMMON)/gmap.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/message.o \
	$(COMMON)/misc.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/references.o \
	$(COMMON)/sort.o \
	$(COMMON)/susymmetries.o \
	$(COMMON)/timing.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	distrib.o \
	input.o \
	input_common.o \
	input_q.o \
	inread.o \
	interpol.o \
	plotxct.o \
	plotxct_common.o \
	read_wannier.o \
	write_xct.o
plotxctdens.x plotxctdens$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/checkbz.o \
	$(COMMON)/fftw.o \
	$(COMMON)/fullbz.o \
	$(COMMON)/genwf.o \
	$(COMMON)/gmap.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/message.o \
	$(COMMON)/misc.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/sort.o \
	$(COMMON)/susymmetries.o \
	$(COMMON)/timing.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	distrib.o \
	input.o \
	input_common.o \
	input_q.o \
	inreaddens.o \
	plotxct_common.o \
	plotxctdens.o \
	write_xct_dens.o
