# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
absh.o absh_m.mod: \
	$(COMMON)/global_m.mod
absorption.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/references_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/write_program_header_m.mod \
	bse_init_m.mod \
	diag_m.mod \
	haydock_m.mod \
	inread_m.mod
absp.o absp_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
absp0.o absp0_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	absp_io_m.mod
absp_io.o absp_io_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
absp_lanczos.o absp_lanczos_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scalapack_m.mod \
	$(COMMON)/timing_m.mod \
	diagonalize_m.mod
algos_kernel.o algos_kernel_m.mod: \
	$(COMMON)/accel_memory_m.mod \
	$(COMMON)/algos_common_m.mod \
	$(COMMON)/message_m.mod \
	$(COMMON)/nrtype_m.mod \
	$(COMMON)/peinfo_m.mod \
	$(COMMON)/push_pop_m.mod
bse_convert.o bse_convert_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/kernel_io_m.mod
bse_init.o bse_init_m.mod: \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	intpts_m.mod
bseascbin.o : \
	$(COMMON)/global_m.mod \
	bse_convert_m.mod
bsebinasc.o : \
	$(COMMON)/global_m.mod \
	bse_convert_m.mod
bsemat_check.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
bsewrite.o bsewrite_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/kernel_io_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
diag.o diag_m.mod: \
	$(COMMON)/evecs_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/genwf_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	absp0_m.mod \
	absp_io_m.mod \
	absp_lanczos_m.mod \
	absp_m.mod \
	diagonalize_m.mod \
	input_fi_m.mod \
	input_q_m.mod \
	intkernel_m.mod \
	intwfn_m.mod \
	vmtxel_m.mod
diagonalize.o diagonalize_m.mod: \
	$(COMMON)/elpa_interface_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/primme_interface_m.mod \
	$(COMMON)/scalapack_hl_m.mod \
	$(COMMON)/scalapack_m.mod
distrib.o distrib_m.mod: \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scalapack_m.mod
distrib_kernel.o distrib_kernel_m.mod: \
	$(COMMON)/createpools_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
epscopy.o epscopy_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/epsread_hdf5_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
epsdiag.o epsdiag_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/epsread_hdf5_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/sort_m.mod
epsmodel.o epsmodel_m.mod: \
	$(COMMON)/global_m.mod
forces.o : \
	$(COMMON)/eqpcor_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	$(COMMON)/write_program_header_m.mod
g_sum.o g_sum_m.mod: \
	$(COMMON)/accel_linalg_m.mod \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	algos_kernel_m.mod
genwf_co.o genwf_co_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/susymmetries_m.mod
genwf_kernel.o genwf_kernel_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/susymmetries_m.mod
gx_sum.o gx_sum_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod
haydock.o haydock_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/genwf_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/random_m.mod \
	$(COMMON)/timing_m.mod \
	absh_m.mod \
	absp0_m.mod \
	input_fi_m.mod \
	input_q_m.mod \
	intkernel_m.mod \
	intwfn_m.mod \
	iterate_m.mod \
	mtxel_jdos_m.mod \
	vmtxel_m.mod
input_co.o input_co_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/eqpcor_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scissors_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
input_co_q.o input_co_q_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/eqpcor_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scissors_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
input_fi.o input_fi_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/eqpcor_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scissors_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	distrib_m.mod \
	intpts_m.mod
input_kernel.o input_kernel_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/epsread_hdf5_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/read_rho_vxc_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	distrib_kernel_m.mod
input_q.o input_q_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/eqpcor_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scissors_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
inread.o inread_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/inread_common_m.mod \
	$(COMMON)/references_m.mod \
	$(COMMON)/scissors_m.mod
inread_kernel.o inread_kernel_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/inread_common_m.mod \
	$(COMMON)/references_m.mod \
	algos_kernel_m.mod
inteqp.o : \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/write_program_header_m.mod \
	bse_init_m.mod \
	input_fi_m.mod \
	input_q_m.mod \
	inread_m.mod \
	intwfn_m.mod
interp.o interp_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/lapack_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/tile_m.mod
intkernel.o intkernel_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/cells_m.mod \
	$(COMMON)/checkgriduniformity_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/kernel_io_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/vcoul_generator_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	epsdiag_m.mod \
	interp_m.mod \
	intpts_m.mod
intpts.o intpts_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/lapack_m.mod \
	$(COMMON)/sort_m.mod
intwfn.o intwfn_m.mod: \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/genwf_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	genwf_co_m.mod \
	input_co_m.mod \
	input_co_q_m.mod \
	interp_m.mod \
	intpts_m.mod \
	mtxel_t_m.mod
iterate.o iterate_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/scalapack_m.mod
kernel.o : \
	$(COMMON)/accel_fft_m.mod \
	$(COMMON)/accel_memory_m.mod \
	$(COMMON)/check_screening_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/references_m.mod \
	$(COMMON)/vcoul_generator_m.mod \
	$(COMMON)/write_program_header_m.mod \
	algos_kernel_m.mod \
	bsewrite_m.mod \
	epscopy_m.mod \
	genwf_kernel_m.mod \
	input_kernel_m.mod \
	inread_kernel_m.mod \
	mtxel_kernel_m.mod \
	mtxel_tddft_m.mod \
	sortbyq_m.mod
mtxel_jdos.o mtxel_jdos_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/random_m.mod
mtxel_kernel.o mtxel_kernel_m.mod: \
	$(COMMON)/accel_fft_m.mod \
	$(COMMON)/accel_memory_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/misc_m.mod \
	algos_kernel_m.mod \
	g_sum_m.mod \
	gx_sum_m.mod \
	w_sum_m.mod
mtxel_md.o mtxel_md_m.mod: \
	$(COMMON)/global_m.mod
mtxel_t.o mtxel_t_m.mod: \
	$(COMMON)/global_m.mod
mtxel_tddft.o mtxel_tddft_m.mod: \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	g_sum_m.mod \
	gx_sum_m.mod
setup_subsampling_csi.o : \
	$(COMMON)/checkbz_m.mod \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/irrbz_m.mod \
	$(COMMON)/random_m.mod \
	$(COMMON)/subgrp_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
sortbyq.o sortbyq_m.mod: \
	$(COMMON)/global_m.mod
summarize_eigenvectors.o : \
	$(COMMON)/evecs_m.mod \
	$(COMMON)/global_m.mod
vmtxel.o vmtxel_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/mtxel_optical_m.mod
vmtxel_main.o : \
	$(COMMON)/fullbz_m.mod \
	$(COMMON)/genwf_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod \
	$(COMMON)/write_program_header_m.mod \
	input_fi_m.mod \
	input_q_m.mod \
	vmtxel_m.mod
w_sum.o w_sum_m.mod: \
	$(COMMON)/accel_linalg_m.mod \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	algos_kernel_m.mod

#Link dependencies:
absorption.x absorption$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/bessel.o \
	$(COMMON)/bgw_mpi.o \
	$(COMMON)/blas.o \
	$(COMMON)/cells.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/checkbz.o \
	$(COMMON)/checkgriduniformity.o \
	$(COMMON)/elpa_interface.o \
	$(COMMON)/epsread_hdf5.o \
	$(COMMON)/eqpcor.o \
	$(COMMON)/evecs.o \
	$(COMMON)/fft_parallel.o \
	$(COMMON)/fftw.o \
	$(COMMON)/fullbz.o \
	$(COMMON)/genwf.o \
	$(COMMON)/gmap.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/inread_common.o \
	$(COMMON)/io_utils.o \
	$(COMMON)/kernel_io.o \
	$(COMMON)/lapack.o \
	$(COMMON)/message.o \
	$(COMMON)/minibzaverage.o \
	$(COMMON)/misc.o \
	$(COMMON)/mtxel_optical.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/nvtx.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/primme_bindings.o \
	$(COMMON)/primme_interface.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/references.o \
	$(COMMON)/scalapack.o \
	$(COMMON)/scalapack_hl.o \
	$(COMMON)/scissors.o \
	$(COMMON)/sort.o \
	$(COMMON)/splines.o \
	$(COMMON)/susymmetries.o \
	$(COMMON)/tile.o \
	$(COMMON)/timing.o \
	$(COMMON)/trunc_cell_box.o \
	$(COMMON)/trunc_cell_box_d.o \
	$(COMMON)/trunc_cell_wire.o \
	$(COMMON)/trunc_scell_box_d.o \
	$(COMMON)/vcoul_generator.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	absh.o \
	absorption.o \
	absp.o \
	absp0.o \
	absp_io.o \
	absp_lanczos.o \
	bse_init.o \
	diag.o \
	diagonalize.o \
	distrib.o \
	epsdiag.o \
	genwf_co.o \
	haydock.o \
	input_co.o \
	input_co_q.o \
	input_fi.o \
	input_q.o \
	inread.o \
	interp.o \
	intkernel.o \
	intpts.o \
	intwfn.o \
	iterate.o \
	mtxel_jdos.o \
	mtxel_t.o \
	vmtxel.o
bseascbin.x bseascbin$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/kernel_io.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	bse_convert.o \
	bseascbin.o
bsebinasc.x bsebinasc$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/kernel_io.o \
	$(COMMON)/sort.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	bse_convert.o \
	bsebinasc.o
bsemat_check.x bsemat_check$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/misc.o \
	bsemat_check.o
forces.x forces$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/check_inversion.o \
	$(COMMON)/eqpcor.o \
	$(COMMON)/sort.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	forces.o
inteqp.x inteqp$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/checkbz.o \
	$(COMMON)/eqpcor.o \
	$(COMMON)/fftw.o \
	$(COMMON)/fullbz.o \
	$(COMMON)/genwf.o \
	$(COMMON)/gmap.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/inread_common.o \
	$(COMMON)/io_utils.o \
	$(COMMON)/lapack.o \
	$(COMMON)/message.o \
	$(COMMON)/misc.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/references.o \
	$(COMMON)/scalapack.o \
	$(COMMON)/scissors.o \
	$(COMMON)/sort.o \
	$(COMMON)/splines.o \
	$(COMMON)/susymmetries.o \
	$(COMMON)/tile.o \
	$(COMMON)/timing.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	bse_init.o \
	distrib.o \
	genwf_co.o \
	input_co.o \
	input_co_q.o \
	input_fi.o \
	input_q.o \
	inread.o \
	inteqp.o \
	interp.o \
	intpts.o \
	intwfn.o \
	mtxel_t.o
kernel.x kernel$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/accel_fft.o \
	$(COMMON)/accel_linalg.o \
	$(COMMON)/accel_memory.o \
	$(COMMON)/algos_common.o \
	$(COMMON)/bessel.o \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/check_screening.o \
	$(COMMON)/checkbz.o \
	$(COMMON)/createpools.o \
	$(COMMON)/epsread_hdf5.o \
	$(COMMON)/fft_parallel.o \
	$(COMMON)/fftw.o \
	$(COMMON)/fullbz.o \
	$(COMMON)/gmap.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/inread_common.o \
	$(COMMON)/io_utils.o \
	$(COMMON)/kernel_io.o \
	$(COMMON)/message.o \
	$(COMMON)/minibzaverage.o \
	$(COMMON)/misc.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/read_rho_vxc.o \
	$(COMMON)/references.o \
	$(COMMON)/scalapack.o \
	$(COMMON)/sort.o \
	$(COMMON)/susymmetries.o \
	$(COMMON)/timing.o \
	$(COMMON)/trunc_cell_box.o \
	$(COMMON)/trunc_cell_box_d.o \
	$(COMMON)/trunc_cell_wire.o \
	$(COMMON)/trunc_scell_box_d.o \
	$(COMMON)/typedefs.o \
	$(COMMON)/vcoul_generator.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	algos_kernel.o \
	bsewrite.o \
	distrib_kernel.o \
	epscopy.o \
	g_sum.o \
	genwf_kernel.o \
	gx_sum.o \
	input_kernel.o \
	inread_kernel.o \
	kernel.o \
	mtxel_kernel.o \
	mtxel_tddft.o \
	sortbyq.o \
	w_sum.o
setup_subsampling_csi.x setup_subsampling_csi$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/checkbz.o \
	$(COMMON)/fullbz.o \
	$(COMMON)/irrbz.o \
	$(COMMON)/misc.o \
	$(COMMON)/random.o \
	$(COMMON)/sort.o \
	$(COMMON)/subgrp.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	setup_subsampling_csi.o
summarize_eigenvectors.x summarize_eigenvectors$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/evecs.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/message.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/wfn_io_hdf5.o \
	summarize_eigenvectors.o
vmtxel.x vmtxel$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/blas.o \
	$(COMMON)/check_inversion.o \
	$(COMMON)/checkbz.o \
	$(COMMON)/eqpcor.o \
	$(COMMON)/fftw.o \
	$(COMMON)/fullbz.o \
	$(COMMON)/genwf.o \
	$(COMMON)/gmap.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/input_utils.o \
	$(COMMON)/io_utils.o \
	$(COMMON)/lapack.o \
	$(COMMON)/message.o \
	$(COMMON)/misc.o \
	$(COMMON)/mtxel_optical.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/push_pop.o \
	$(COMMON)/random.o \
	$(COMMON)/scalapack.o \
	$(COMMON)/scissors.o \
	$(COMMON)/sort.o \
	$(COMMON)/splines.o \
	$(COMMON)/susymmetries.o \
	$(COMMON)/timing.o \
	$(COMMON)/version.o \
	$(COMMON)/wfn_io_hdf5.o \
	$(COMMON)/wfn_rho_vxc_io.o \
	$(COMMON)/write_program_header.o \
	distrib.o \
	input_fi.o \
	input_q.o \
	intpts.o \
	vmtxel.o \
	vmtxel_main.o
