# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
$(COMMON)/accel_fft.o $(COMMON)/accel_fft_m.mod: \
	$(COMMON)/accel_memory_m.mod \
	$(COMMON)/algos_common_m.mod \
	$(COMMON)/message_m.mod \
	$(COMMON)/nrtype_m.mod \
	$(COMMON)/peinfo_m.mod \
	$(COMMON)/push_pop_m.mod
$(COMMON)/accel_linalg.o $(COMMON)/accel_linalg_m.mod: \
	$(COMMON)/algos_common_m.mod \
	$(COMMON)/blas_m.mod \
	$(COMMON)/message_m.mod \
	$(COMMON)/nrtype_m.mod
$(COMMON)/accel_memory.o $(COMMON)/accel_memory_m.mod: \
	$(COMMON)/algos_common_m.mod \
	$(COMMON)/typedefs_m.mod
$(COMMON)/algos_common.o $(COMMON)/algos_common_m.mod: \
	$(COMMON)/message_m.mod \
	$(COMMON)/peinfo_m.mod \
	$(COMMON)/push_pop_m.mod
$(COMMON)/bessel.o $(COMMON)/bessel_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/bgw_mpi.o $(COMMON)/bgw_mpi_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/cells.o $(COMMON)/cells_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/check_inversion.o $(COMMON)/check_inversion_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/check_screening.o $(COMMON)/check_screening_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/checkbz.o $(COMMON)/checkbz_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
$(COMMON)/checkgriduniformity.o $(COMMON)/checkgriduniformity_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/createpools.o $(COMMON)/createpools_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/elpa_interface.o $(COMMON)/elpa_interface_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/scalapack_m.mod
$(COMMON)/epsread_hdf5.o $(COMMON)/epsread_hdf5_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/scalapack_m.mod \
	$(COMMON)/timing_m.mod
$(COMMON)/epswrite_hdf5.o $(COMMON)/epswrite_hdf5_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod
$(COMMON)/eqpcor.o $(COMMON)/eqpcor_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/evecs.o $(COMMON)/evecs_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/message_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod
$(COMMON)/fft_parallel.o $(COMMON)/fft_parallel_m.mod: \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod
$(COMMON)/fftw.o $(COMMON)/fftw_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/timing_m.mod
$(COMMON)/fftw_inc.o $(COMMON)/fftw_inc_m.mod: \
	$(COMMON)/timing_m.mod
$(COMMON)/find_kpt_match.o $(COMMON)/find_kpt_match_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/fixwings.o $(COMMON)/fixwings_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/fullbz.o $(COMMON)/fullbz_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
$(COMMON)/genwf.o $(COMMON)/genwf_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/input_utils_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/random_m.mod \
	$(COMMON)/sort_m.mod \
	$(COMMON)/susymmetries_m.mod
$(COMMON)/global.o $(COMMON)/global_m.mod: \
	$(COMMON)/message_m.mod \
	$(COMMON)/nrtype_m.mod \
	$(COMMON)/os_m.mod \
	$(COMMON)/peinfo_m.mod \
	$(COMMON)/push_pop_m.mod \
	$(COMMON)/scalapack_aux_m.mod \
	$(COMMON)/timing_m.mod \
	$(COMMON)/typedefs_m.mod
$(COMMON)/gmap.o $(COMMON)/gmap_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
$(COMMON)/groupk.o $(COMMON)/groupk_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/hdf5_io.o $(COMMON)/hdf5_io_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_data_m.mod \
	$(COMMON)/hdf5_io_safe_m.mod
$(COMMON)/hdf5_io_data.o $(COMMON)/hdf5_io_data_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_safe_m.mod
$(COMMON)/hdf5_io_safe.o $(COMMON)/hdf5_io_safe_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/input_utils.o $(COMMON)/input_utils_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod
$(COMMON)/inread_common.o $(COMMON)/inread_common_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/inversion.o $(COMMON)/inversion_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/lapack_m.mod \
	$(COMMON)/scalapack_m.mod
$(COMMON)/io_utils.o $(COMMON)/io_utils_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/irrbz.o $(COMMON)/irrbz_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
$(COMMON)/kernel_io.o $(COMMON)/kernel_io_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/wfn_io_hdf5_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
$(COMMON)/message.o $(COMMON)/message_m.mod: \
	$(COMMON)/nrtype_m.mod \
	$(COMMON)/os_m.mod \
	$(COMMON)/peinfo_m.mod
$(COMMON)/minibzaverage.o $(COMMON)/minibzaverage_m.mod: \
	$(COMMON)/bessel_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
$(COMMON)/misc.o $(COMMON)/misc_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod
$(COMMON)/mtxel_optical.o $(COMMON)/mtxel_optical_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/norm.o $(COMMON)/norm_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod
$(COMMON)/os.o $(COMMON)/os_m.mod: \
	$(COMMON)/nrtype_m.mod
$(COMMON)/peinfo.o $(COMMON)/peinfo_m.mod: \
	$(COMMON)/nrtype_m.mod
$(COMMON)/primme_bindings.o $(COMMON)/primme_bindings_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/primme_interface.o $(COMMON)/primme_interface_m.mod: \
	$(COMMON)/bgw_mpi_m.mod \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/nvtx_m.mod \
	$(COMMON)/primme_bindings_m.mod
$(COMMON)/print_version_info.o : \
	$(COMMON)/global_m.mod \
	$(COMMON)/version_m.mod
$(COMMON)/push_pop.o $(COMMON)/push_pop_m.mod: \
	$(COMMON)/message_m.mod \
	$(COMMON)/nrtype_m.mod \
	$(COMMON)/peinfo_m.mod
$(COMMON)/random.o $(COMMON)/random_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/read_cube.o $(COMMON)/read_cube_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/read_matrix.o $(COMMON)/read_matrix_m.mod: \
	$(COMMON)/epsread_hdf5_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/scalapack_m.mod
$(COMMON)/read_rho_vxc.o $(COMMON)/read_rho_vxc_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/gmap_m.mod \
	$(COMMON)/wfn_rho_vxc_io_m.mod
$(COMMON)/references.o $(COMMON)/references_m.mod: \
	$(COMMON)/message_m.mod \
	$(COMMON)/nrtype_m.mod \
	$(COMMON)/os_m.mod \
	$(COMMON)/peinfo_m.mod \
	$(COMMON)/push_pop_m.mod
$(COMMON)/scalapack.o $(COMMON)/scalapack_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/scalapack_hl.o $(COMMON)/scalapack_hl_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/scalapack_m.mod
$(COMMON)/scissors.o $(COMMON)/scissors_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/splines_m.mod
$(COMMON)/sort.o $(COMMON)/sort_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/spinor_symmetries.o $(COMMON)/spinor_symmetries_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/random_m.mod
$(COMMON)/splines.o $(COMMON)/splines_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/subgrp.o $(COMMON)/subgrp_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
$(COMMON)/susymmetries.o $(COMMON)/susymmetries_m.mod: \
	$(COMMON)/blas_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/random_m.mod
$(COMMON)/symmetries.o $(COMMON)/symmetries_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod \
	$(COMMON)/sort_m.mod
$(COMMON)/test_evecs.o : \
	$(COMMON)/evecs_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod
$(COMMON)/test_primme.o : \
	$(COMMON)/bgw_mpi_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/primme_interface_m.mod \
	$(COMMON)/write_program_header_m.mod
$(COMMON)/tile.o $(COMMON)/tile_m.mod: \
	$(COMMON)/global_m.mod
$(COMMON)/timing.o $(COMMON)/timing_m.mod: \
	$(COMMON)/message_m.mod \
	$(COMMON)/nrtype_m.mod \
	$(COMMON)/os_m.mod \
	$(COMMON)/peinfo_m.mod \
	$(COMMON)/push_pop_m.mod
$(COMMON)/trunc_cell_box.o $(COMMON)/trunc_cell_box_m.mod: \
	$(COMMON)/fft_parallel_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
$(COMMON)/trunc_cell_box_d.o $(COMMON)/trunc_cell_box_d_m.mod: \
	$(COMMON)/fft_parallel_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
$(COMMON)/trunc_cell_wire.o $(COMMON)/trunc_cell_wire_m.mod: \
	$(COMMON)/bessel_m.mod \
	$(COMMON)/fft_parallel_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
$(COMMON)/trunc_scell_box_d.o $(COMMON)/trunc_scell_box_d_m.mod: \
	$(COMMON)/fft_parallel_m.mod \
	$(COMMON)/fftw_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/misc_m.mod
$(COMMON)/typedefs.o $(COMMON)/typedefs_m.mod: \
	$(COMMON)/message_m.mod \
	$(COMMON)/nrtype_m.mod \
	$(COMMON)/push_pop_m.mod
$(COMMON)/vcoul_generator.o $(COMMON)/vcoul_generator_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/minibzaverage_m.mod \
	$(COMMON)/random_m.mod \
	$(COMMON)/trunc_cell_box_d_m.mod \
	$(COMMON)/trunc_cell_box_m.mod \
	$(COMMON)/trunc_cell_wire_m.mod \
	$(COMMON)/trunc_scell_box_d_m.mod
$(COMMON)/wfn_io_hdf5.o $(COMMON)/wfn_io_hdf5_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod
$(COMMON)/wfn_rho_vxc_io.o $(COMMON)/wfn_rho_vxc_io_m.mod: \
	$(COMMON)/check_inversion_m.mod \
	$(COMMON)/global_m.mod \
	$(COMMON)/sort_m.mod
$(COMMON)/wfn_rho_vxc_io_inc.o $(COMMON)/wfn_rho_vxc_io_inc_m.mod: \
	$(COMMON)/timing_m.mod
$(COMMON)/write_matrix.o $(COMMON)/write_matrix_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/hdf5_io_m.mod \
	$(COMMON)/io_utils_m.mod \
	$(COMMON)/scalapack_m.mod \
	$(COMMON)/timing_m.mod
$(COMMON)/write_program_header.o $(COMMON)/write_program_header_m.mod: \
	$(COMMON)/global_m.mod \
	$(COMMON)/version_m.mod

#Link dependencies:
$(COMMON)/print_version_info.x $(COMMON)/print_version_info$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/print_version_info.o \
	$(COMMON)/version.o
$(COMMON)/test_evecs.x $(COMMON)/test_evecs$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/evecs.o \
	$(COMMON)/hdf5_io.o \
	$(COMMON)/hdf5_io_data.o \
	$(COMMON)/hdf5_io_safe.o \
	$(COMMON)/message.o \
	$(COMMON)/nrtype.o \
	$(COMMON)/os.o \
	$(COMMON)/peinfo.o \
	$(COMMON)/test_evecs.o \
	$(COMMON)/wfn_io_hdf5.o
$(COMMON)/test_primme.x $(COMMON)/test_primme$(FLAVOR).x: \
	$(GLOBALOBJS) \
	$(COMMON)/bgw_mpi.o \
	$(COMMON)/blas.o \
	$(COMMON)/nvtx.o \
	$(COMMON)/primme_bindings.o \
	$(COMMON)/primme_interface.o \
	$(COMMON)/test_primme.o \
	$(COMMON)/version.o \
	$(COMMON)/write_program_header.o
