## Makefile (Felipe H. da Jornada -  Aug 2014)
## This is not the Makefile that comes with voro++.
## It has been simplified and made compatible with the arch.mk of BerkeleyGW.

# Load the common configuration file
PREFIX=../../..
include $(PREFIX)/Common/common-rules.mk
