# This file was generated by make_deps.py. Do not edit this directly.


#Compile dependencies:
CumExp.o : \
	$(COMMON)/global_m.mod

#Link dependencies:
kptsummedspectralfcn.x kptsummedspectralfcn$(FLAVOR).x: \
	$(GLOBALOBJS) \
	CumExp.o
